name: Fetch Cybersecurity News

on:
  schedule:
    - cron: '0 */6 * * *'  # svakih 6 sati
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Run news fetcher
        run: python3 fetch_news.py

      - name: Commit and push changes
        run: |
          git config user.name "leonorabot"
          git config user.email "actions@github.com"
          git add docs/security-news/
          git commit -m "📰 Security News Update - $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
